### ISSUE TITLE
Server Crashes when triggering an index-rebuild

### ISSUE THREAD

**Issue by simpros** [your-own-stuff/yos-server#13]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1073450]

goroutine 4488 [running]:
github.com/pocketbase/pocketbase/daos.(*Dao).ConcurrentDB(...)
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/base.go:69
github.com/pocketbase/pocketbase/daos.(*Dao).DB(...)
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/base.go:61
github.com/pocketbase/pocketbase/daos.(*Dao).ModelQuery(0x0, {0x1f9fa20?, 0x4000a172b0?})
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/base.go:107 +0x40
github.com/pocketbase/pocketbase/daos.(*Dao).CollectionQuery(...)
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/collection.go:18
github.com/pocketbase/pocketbase/daos.(*Dao).FindCollectionByNameOrId(0x0, {0x15cf335, 0xc})
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/collection.go:41 +0x58
github.com/pocketbase/pocketbase/daos.(*Dao).RecordQuery(0x0, {0x13587a0?, 0x40000529a0?})
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/record.go:40 +0x64
github.com/pocketbase/pocketbase/daos.(*Dao).FindFirstRecordByData(0x0, {0x15cf335, 0xc}, {0x15c4f01, 0x4}, {0x13587a0, 0x1f836f0})
        /go/pkg/mod/github.com/pocketbase/pocketbase@v0.22.6/daos/record.go:240 +0x64
github.com/your-own-stuff/yos-server/yos.GenerateIndex(0x4000a65c60, {0x4000cd48a0, 0xf})
        /workspace/yos/generate-index.go:13 +0x58
created by main.main.func2.(*Server).GetRoutes.2 in goroutine 4482
        /workspace/yos/yos.go:52 +0xe8
exit status 2
```

**Comment by simpros** [comment]
It looks like the Dao is nil 🤔 
![CleanShot 2024-04-03 at 08 16 37](https://github.com/your-own-stuff/yos-server/assets/38320875/1d85178c-b74f-4b11-83ce-312d173c9100)
